Include linux/time.h for musl where timespec data type is defined explicitly
This is necessary to address the following error with musl C library:
error: invalid application of 'sizeof' to incomplete type
'linux_syscall_support::timespec'